const light = {
  primaryGreen: "#AFF4C6",
  primaryDarkGreen: "#14AE5C",
  primaryButtonGreen: "#83B494",
  secondaryGreen: "#83B494",
  secondaryDarkGreen: "#A0CFB5",
  primarySwitchOff: "#797979",
  blackTextColor: "#000",
  greyTextColor: "#98C9A9",
  darkGreenTextColor: "#0E733D",
  whiteBackgroundColor: "#FFFFFFFF",
  progressBarColor: "#dddddd",
  spendingButton: "#FFFFFF",
  overlayColor: "#000000",
  placeholderColor: "#696969",
  cardBackground: "#454545",
  graphsColor: "#f6f6f6",
};
const dark = {
  primaryGreen: "#AFF4C6",
  primaryDarkGreen: "#14AE5C",
  primaryButtonGreen: "#83B494",
  secondaryGreen: "#83B494",
  secondaryDarkGreen: "#A0CFB5",
  primarySwitchOff: "#797979",
  blackTextColor: "#FFFFFF",
  greyTextColor: "#98C9A9",
  darkGreenTextColor: "#16b25f",
  whiteBackgroundColor: "#454545",
  progressBarColor: "#dddddd",
  spendingButton: "#FFFFFF",
  overlayColor: "#000000",
  placeholderColor: "#FFFFFFFF",
  cardBackground: "#FFFFFFFF",
  graphsColor: "#F5F5F5",
};

export const colorss = { light, dark };
